### ISSUE TITLE
Minichat Attach button Icon

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#119]
![154576522-aea9d243-8af0-4d5b-a6a7-d5f10f47a787](https://user-images.githubusercontent.com/88825506/154655492-c6e06c58-5d27-4c45-b1ba-582a8f0f50f6.png)

**Comment by RezaUFC** [comment]
Icon is not visible or is missing from the place. 

![image](https://user-images.githubusercontent.com/88825506/154722437-6a668b86-73cc-466a-8d12-1cbbd00549eb.png)

**Comment by pureinx** [comment]
@RezaUFC we dont have attachment feature for the yollochat, only for the octolit.

**Comment by RezaUFC** [comment]
attach button on minichat is still missing
