### ISSUE TITLE
Reset password issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#124]
![154580498-95f6cd22-1426-4e78-bae9-7606e238fe42](https://user-images.githubusercontent.com/88825506/154655845-81555519-d2db-49c6-a8a1-7ad37e690e0a.png)

**Comment by pureinx** [comment]
@RezaUFC I cant reproduce this bug, can you record a video?

**Comment by RezaUFC** [comment]
this is ok, Navid solved the Issue,
