### ISSUE TITLE
Unknown company error! On Minichat

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#125]
I just clear my cache and after I have got this error all the time on the minichat. 

![Screenshot 2022-02-18 182457](https://user-images.githubusercontent.com/88825506/154722711-978d1c8c-5eaa-4565-9fca-aa052dcd71af.jpg)

**Comment by RezaUFC** [comment]
I clear mu cache but the history of my tickets are still there

![image](https://user-images.githubusercontent.com/88825506/154723223-328a04f1-9d69-4dda-9770-d48955643e56.png)

**Comment by pureinx** [comment]
@RezaUFC actually history of tickets are not in the cache, it is in localstorage
