### ISSUE TITLE
Import CSV file Issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#13]
After selecting CSV file to import clients, Nothing will add to the list of client from imported file.

![image](https://user-images.githubusercontent.com/88825506/148534671-ea7ea2bc-fbc6-4c64-a58f-7ebd7e6ec62a.png)
![image](https://user-images.githubusercontent.com/88825506/148534696-cb4302c1-db55-41da-8e3f-a8d02f2b3e2f.png)

**Comment by navid-farjad** [comment]
please send me csv file
