### ISSUE TITLE
Member Date picker is not working 

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#133]
the date picker is not working and not making any changes

https://user-images.githubusercontent.com/88825506/154993471-e1200dfd-da05-43c4-a79f-5d1c2693dc93.mp4

**Comment by RezaUFC** [comment]
the date picker is making changes on the member data, but on the date number showing it doesn't show the correct date that has been chosen.

**Comment by pureinx** [comment]
@RezaUFC Online Time and Date is not the same

**Comment by navid-farjad** [comment]
@pureinx he mean after selecting date in calendar, calendar input is resetting!

**Comment by pureinx** [comment]
@navid-farjad fixed! you can deploy. @RezaUFC
