### ISSUE TITLE
Minichat is missing on Article page

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#147]
the minichat is enable for article page, but the minichat is not there.
![image](https://user-images.githubusercontent.com/88825506/155696640-580e1e29-a870-4b3d-9ee2-fb842982ec54.png)
![image](https://user-images.githubusercontent.com/88825506/155696666-d6bf6b8f-1730-44ef-bf5c-36d4a5729e03.png)

**Comment by pureinx** [comment]
Pushed to master, should be fixed. @RezaUFC can test when @navid-farjad deploy
