### ISSUE TITLE
Context need to show on the ticket info 

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#148]
in case that there is no added context , but the full name and email is there, we need to see this on the info submitted to the ticket.
![image](https://user-images.githubusercontent.com/88825506/155698102-7145cf9f-9dd1-40f9-ab9d-0daae332a9a7.png)

**Comment by navid-farjad** [comment]
@pureinx we dont need name and email here! please just dont send empty context

**Comment by pureinx** [comment]
This is fixed, @RezaUFC can test when @navid-farjad deploy it
