### ISSUE TITLE
Offline message is not Working

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#149]
I'm logout and offline with all my accounts, I have set the offline message in the dashboard, 
But after user is submitting the ticket on minichat, will not showing any offline message. 
![image](https://user-images.githubusercontent.com/88825506/155705449-545dea45-a27e-4010-8239-60ce85a15f90.png)

**Comment by pureinx** [comment]
Guess this may be backend issue because on front-end side I have just a message and no logic to set this message in the chat.
