### ISSUE TITLE
Minichat - User waiting Number Issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#150]
the number of users waiting is nor dynamic, as I have submitted ticket to the minichat with 4 different browser, and still showing only number 1

![image](https://user-images.githubusercontent.com/88825506/155705935-e40c3055-eaf4-4a89-9d83-8c96322d6b7f.png)
![image](https://user-images.githubusercontent.com/88825506/155705997-cb604089-1102-4724-968c-6fba9f8b4c2d.png)
![image](https://user-images.githubusercontent.com/88825506/155706023-3a360fe7-ecc1-4063-baab-b64081e7c8d1.png)

**Comment by pureinx** [comment]
@navid-farjad it might be backend issue, I subscribed on LineChannel but when I open new browsers and create ticket, this socket channel doesnt give me any data

**Comment by navid-farjad** [comment]
@pureinx  this socket will give you data when agent close ticket
subscribe for LineChannel with line_client_6457458   (client id)

**Comment by navid-farjad** [comment]
@pureinx also on ticket object you have "inline"
when you are not in chat page in minichat. please hide "User waiting"
