### ISSUE TITLE
Minichat - Estimated time Issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#151]
there is estimated time on minichat but there is nothing to show as time or waiting or any message, 
Also there is no setting for this feature on dashboard - minichat settings

![image](https://user-images.githubusercontent.com/88825506/155706353-b9f97492-9789-4126-a9fa-a73d05689460.png)

![image](https://user-images.githubusercontent.com/88825506/155706400-997ec618-4cfd-4866-8ed5-8b8812882089.png)

**Comment by pureinx** [comment]
Added "reply time" to the Mini Chat Installation settings
