### ISSUE TITLE
Wrong Tittle for Customer Labels

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#2]
Report Section, Tab "Customer Labels" has wrong tittle "Ticket Labels". 

![image](https://user-images.githubusercontent.com/88825506/148511977-61aebf15-4578-45ec-afc2-e2ab3833f20d.png)

**Comment by navid-farjad** [comment]
You are in tickets !!

**Comment by RezaUFC** [comment]
✅ Done!
