### ISSUE TITLE
Ticket Message Wrong Time 

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#20]
submitted messages on the ticket has wrong time and also all the messages are in different time range. 

![image](https://user-images.githubusercontent.com/88825506/148551856-87d2cb59-5f53-4d15-b837-821ab55808b2.png)

**Comment by navid-farjad** [comment]
dayjs is giving sync data! @pureinx

**Comment by RezaUFC** [comment]
✅ Done!
