### ISSUE TITLE
Create New Ticket (Note Issue)

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#25]
The typed text in to the note field is not showing anywhere to the new ticket that was created, 
![image](https://user-images.githubusercontent.com/88825506/148581117-2000cf39-bae1-4623-a1d9-bf820a4cf48f.png)

**Comment by RezaUFC** [comment]
If this note is not necessary to be there just remove it or to be added as not to the client ticket on the left side.

**Comment by navid-farjad** [comment]
the note goes as first message
