### ISSUE TITLE
New user added to company Admin Error

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#38]
there is an error that is showing all the time for the new user after reloading the page. 

![image](https://user-images.githubusercontent.com/88825506/148741107-208237d1-067d-4f9f-9fd2-0861caec5601.png)

**Comment by RezaUFC** [comment]
![image](https://user-images.githubusercontent.com/88825506/148746695-a91b29e0-daad-4e3c-ab69-90aa6470e8a8.png)

**Comment by navid-farjad** [comment]
please check it again
