### ISSUE TITLE
After ticket assigned, issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#58]
after i assign the ticket to my self nothing change on the appearance of the ticket, the button for assign to me is still there - and even the message is going as Note - even after reload the page nothing will change 

![image](https://user-images.githubusercontent.com/88825506/149315295-073bf14b-45a7-4149-8a6e-ae045f4fdbd2.png)

**Comment by RezaUFC** [comment]
![image](https://user-images.githubusercontent.com/88825506/149315683-5cd55d4d-bd27-4fa9-b0be-4ad6cff73d20.png)

**Comment by navid-farjad** [comment]
also after asign to me assign dropdown should change
