### ISSUE TITLE
Create New ticket, Issue

### ISSUE THREAD

**Issue by RezaUFC** [YolloChat/public_issues#8]
Adding labels to the new ticket, at first click the labels are assigned, but if remove them and want to add the again is not adding. 
This issue for some labels are working correct and for some is not working!!!

https://user-images.githubusercontent.com/88825506/148524181-63e660da-3bea-48ea-abbc-7ed6ac0e4920.mp4

**Comment by navid-farjad** [comment]
@pureinx please push to develop and close the issue @RezaUFC will check it
